kind: Service
apiVersion: v1
metadata:
  name: "gosayhello"
spec:
  selector:
    app: "gosayhello"
  ports:
    - protocol: "TCP"
      port: 9999
      targetPort: 9999
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosayhello-deployment
  labels:
    app: gosayhello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gosayhello
  template:
    metadata:
      labels:
        app: gosayhello
    spec:
      containers:
      - name: gosayhello
        image: brucelu/gosayhello
        ports:
        - containerPort: 9999
        imagePullPolicy: Always
      